apiVersion: v1
kind: Service
metadata:
  name: {{ include "gcsb-connect-sap.fullname" . }}-apiconfig
  labels:
    {{- include "gcsb-connect-sap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiconfig.service.type }}
  ports:
    - port: {{ .Values.apiconfig.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gcsb-connect-sap.selectorLabels-apiconfig" . | nindent 4 }}
