{{ $fullname := include "gcsb-connect-sap.fullname" . }}
{{ $labels := include "gcsb-connect-sap.labels" . }}

{{- if .Values.persistence.enabled -}}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullname }}-{{ .Values.persistence.name }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}

---