{{ $fullname := include "gcsb-connect-sap.fullname" . }}
{{ $labels := include "gcsb-connect-sap.labels" . }}

{{- range $secret := .Values.secrets}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-{{$secret.name}}
  labels:
    {{- $labels | nindent 4 }}
type: {{$secret.type}}
stringData:
  {{- toYaml $secret.stringData | nindent 2}}

{{- end}}